# Generated by Django 3.0.7 on 2020-06-30 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField(default=0, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.CharField(max_length=20)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('parking', models.CharField(default=None, max_length=20)),
                ('sqft', models.IntegerField(blank=True)),
                ('photo_main', models.ImageField(default='default.jpg', upload_to='property_images')),
                ('photo_1', models.ImageField(blank=True, upload_to='property_images')),
                ('photo_2', models.ImageField(blank=True, upload_to='property_images')),
                ('photo_3', models.ImageField(blank=True, upload_to='property_images')),
                ('photo_4', models.ImageField(blank=True, upload_to='property_images')),
                ('photo_5', models.ImageField(blank=True, upload_to='property_images')),
                ('photo_6', models.ImageField(blank=True, upload_to='property_images')),
                ('is_published', models.BooleanField(default=1)),
                ('list_date', models.CharField(max_length=30)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.Realtor')),
            ],
        ),
    ]
