# Generated by Django 3.0.7 on 2020-06-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='parking',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
