# Generated by Django 3.0.7 on 2020-06-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200630_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='parking',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
